/** OpenFootball / our DB team name → Onside FIFA 3-letter code (WC 2026). */
export const TEAM_ONSIDE_CODES: Record<string, string> = {
  Mexico: "mex",
  "South Africa": "rsa",
  "South Korea": "kor",
  "Czech Republic": "cze",
  Canada: "can",
  "Bosnia & Herzegovina": "bih",
  Qatar: "qat",
  Switzerland: "sui",
  Brazil: "bra",
  Morocco: "mar",
  Haiti: "hai",
  Scotland: "sco",
  USA: "usa",
  Paraguay: "par",
  Australia: "aus",
  Turkey: "tur",
  Germany: "ger",
  Curaçao: "cuw",
  "Ivory Coast": "civ",
  Ecuador: "ecu",
  Netherlands: "ned",
  Japan: "jpn",
  Sweden: "swe",
  Tunisia: "tun",
  Belgium: "bel",
  Egypt: "egy",
  Iran: "irn",
  "New Zealand": "nzl",
  Spain: "esp",
  "Cape Verde": "cpv",
  "Saudi Arabia": "ksa",
  Uruguay: "uru",
  France: "fra",
  Senegal: "sen",
  Iraq: "irq",
  Norway: "nor",
  Argentina: "arg",
  Algeria: "alg",
  Austria: "aut",
  Jordan: "jor",
  Portugal: "por",
  "DR Congo": "cod",
  Uzbekistan: "uzb",
  Colombia: "col",
  England: "eng",
  Croatia: "cro",
  Ghana: "gha",
  Panama: "pan",
};

export function getOnsideCode(teamName: string): string | null {
  return TEAM_ONSIDE_CODES[teamName.trim()] ?? null;
}
